### ISSUE TITLE
cardealerdemo-inventory - pom.xml missing 'fabric8:apply' in 'f8-local-deploy'

### ISSUE THREAD

**Issue by kenthua** [jbossdemocentral/jboss-fis-autodealer#1]
The pom.xml in cardealerdemo-inventory doesn't actually deploy the pod because `fabric8:apply` goal is missing from the `f8-local-deploy` profile.  Was this intentional?  After adding this it deployed like the other services/projects.

```
      <id>f8-local-deploy</id>
...
        <defaultGoal>clean install docker:build fabric8:json fabric8:apply</defaultGoal>
```

**Comment by weimeilin79** [comment]
Thanks for picking it up. I have corrected. Thanks!
